{% set name = "docker" %}
{% set version = "20.10.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  folder: docker
  url: https://dockermsft.blob.core.windows.net/dockercontainer/docker-{{ version.replace('.', '-') }}.zip
  sha256: b854d3a3efc159877f8c7e740268f8c4cfdfa6b746e7b331f39ebd2ec91e259f

build:
  number: 0
  skip: true  # [not win]

requirements:
  run:
    - vs2015_runtime

test:
  commands:
    - docker --version

about:
  home: https://github.com/moby/moby
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Docker Engine - Enterprise enables native Docker containers on Windows Server.
  doc_url: https://docs.docker.com/ee/docker-ee/windows/docker-ee/
  dev_url: https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for pyautogen
  recipe-maintainers:
    - ianaobi
    - dhirschfeld
