{% set name = "docker" %}
{% set version = "7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docker-{{ version }}.tar.gz
  sha256: ad8c70e6e3f8926cb8a92619b832b4ea5299e2831c14284663184e200546fa6c

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - requests >=2.26.0
    - urllib3 >=1.26.0
    - pywin32-on-windows >=304  # [win]

test:
  imports:
    - docker
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python library for the Docker Engine API.
  dev_url: https://github.com/docker/docker-py
  license: Apache-2.0
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for pyautogen
  recipe-maintainers:
    - ianaobi
