{% set name = "docker" %}
{% set version = "20.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  folder: docker
  url: https://dockermsft.blob.core.windows.net/dockercontainer/docker-{{ version.replace('.', '-') }}.zip
  sha256: 165fb65be16c92def59bd6997fa2c5fd28694fc2f99ba5971096c5eb9deca085

build:
  number: 0
  skip: true  # [not win]

requirements:
  run:
    - vs2015_runtime

test:
  commands:
    - docker --version

about:
  home: https://github.com/moby/moby
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Docker Engine - Enterprise enables native Docker containers on Windows Server.
  doc_url: https://docs.docker.com/ee/docker-ee/windows/docker-ee/
  dev_url: https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json

extra:
  recipe-maintainers:
    - dhirschfeld
